[package]
name = "component-systems-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
